version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=
    ports:
      - "7701:7700"
    volumes:
      - meilisearch_data:/meili_data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6335:6333"
      - "6336:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  meilisearch_data:
  qdrant_data:
